@baseUrl = http://localhost:3000

### get all messages
GET {{baseUrl}}/messages/
?limit=10
&offset=0

### get messages by id
GET {{baseUrl}}/messages/1

### create message
POST {{baseUrl}}/messages/
Content-Type: application/json

{
    "text": "text for test 2",
    "from": 1,
    "to": 22
}

### update message
PATCH {{baseUrl}}/messages/1
Content-Type: application/json

{
    "text": "update text 1",
    "from": "Pietro",
    "to": "Gustavo"
}

### delete message
DELETE {{baseUrl}}/messages/1